// Speed Match — 200+ questions across 5 categories
// Each question has: category, text, options (4-6 choices)
// 'partner' category = bonus round (20 pts instead of 10)

const FOOD = [
  { text: 'Pick a fruit!', options: ['🍎 Apple', '🍌 Banana', '🍊 Orange', '🍇 Grape', '🍓 Strawberry', '🥭 Mango'] },
  { text: 'Best ice cream flavor?', options: ['Chocolate', 'Vanilla', 'Strawberry', 'Matcha', 'Cookies & Cream', 'Mango'] },
  { text: 'Favorite cuisine?', options: ['Japanese', 'Italian', 'Korean', 'Mexican', 'Thai', 'Indonesian'] },
  { text: 'Pick a drink!', options: ['Boba Tea', 'Coffee', 'Juice', 'Matcha Latte', 'Smoothie', 'Hot Chocolate'] },
  { text: 'Best pizza topping?', options: ['Pepperoni', 'Mushroom', 'Pineapple', 'Cheese Only', 'BBQ Chicken', 'Meat Lovers'] },
  { text: 'Midnight snack?', options: ['Chips', 'Ice Cream', 'Instant Noodles', 'Fruit', 'Cookies', 'Leftover Food'] },
  { text: 'Breakfast pick?', options: ['Pancakes', 'Eggs & Toast', 'Cereal', 'Nasi Goreng', 'Smoothie Bowl', 'Nothing'] },
  { text: 'Best noodle dish?', options: ['Ramen', 'Pad Thai', 'Spaghetti', 'Mie Goreng', 'Pho', 'Udon'] },
  { text: 'Pick a dessert!', options: ['Cake', 'Ice Cream', 'Brownies', 'Mochi', 'Churros', 'Crepe'] },
  { text: 'Coffee order?', options: ['Latte', 'Americano', 'Cappuccino', 'Iced Coffee', 'Mocha', 'No Coffee'] },
  { text: 'Favorite snack?', options: ['Chocolate', 'Chips', 'Nuts', 'Fruit', 'Crackers', 'Candy'] },
  { text: 'Best street food?', options: ['Takoyaki', 'Tacos', 'Satay', 'Crepes', 'Kebab', 'Corn Dog'] },
  { text: 'Pick a vegetable!', options: ['Broccoli', 'Corn', 'Carrot', 'Potato', 'Avocado', 'Spinach'] },
  { text: 'Best soup?', options: ['Chicken Soup', 'Tomato Soup', 'Miso Soup', 'Ramen Broth', 'Mushroom Soup', 'Soto Ayam'] },
  { text: 'Sweet or savory?', options: ['Sweet', 'Savory', 'Both Equally', 'Depends on Mood'] },
  { text: 'Best Asian food?', options: ['Sushi', 'Dim Sum', 'Bibimbap', 'Rendang', 'Curry', 'Fried Rice'] },
  { text: 'Pick a spice level!', options: ['No Spice', 'Mild', 'Medium', 'Spicy', 'Extra Spicy', 'Volcano'] },
  { text: 'Favorite fast food?', options: ['McDonald\'s', 'KFC', 'Burger King', 'Subway', 'Pizza Hut', 'Chick-fil-A'] },
  { text: 'Best cheese?', options: ['Mozzarella', 'Cheddar', 'Parmesan', 'Brie', 'Cream Cheese', 'No Cheese'] },
  { text: 'Pick a cake flavor!', options: ['Chocolate', 'Red Velvet', 'Vanilla', 'Tiramisu', 'Matcha', 'Cheesecake'] },
  { text: 'Best bubble tea flavor?', options: ['Brown Sugar', 'Taro', 'Matcha', 'Classic Milk Tea', 'Fruit Tea', 'Thai Tea'] },
  { text: 'Favorite rice dish?', options: ['Fried Rice', 'Sushi Rice', 'Biryani', 'Nasi Lemak', 'Risotto', 'Rice Bowl'] },
  { text: 'Pick a seafood!', options: ['Shrimp', 'Salmon', 'Tuna', 'Crab', 'Squid', 'No Seafood'] },
  { text: 'Best condiment?', options: ['Ketchup', 'Mayo', 'Soy Sauce', 'Hot Sauce', 'Sambal', 'Mustard'] },
  { text: 'Favorite cooking style?', options: ['Grilled', 'Fried', 'Steamed', 'Baked', 'Raw/Sushi', 'Stir-Fried'] },
  { text: 'Best bread type?', options: ['White Bread', 'Sourdough', 'Croissant', 'Bagel', 'Garlic Bread', 'Naan'] },
  { text: 'Pick a chocolate!', options: ['Milk Chocolate', 'Dark Chocolate', 'White Chocolate', 'Hazelnut', 'Caramel', 'Mint'] },
  { text: 'Best drink for a hot day?', options: ['Iced Tea', 'Smoothie', 'Coconut Water', 'Lemonade', 'Iced Coffee', 'Boba'] },
  { text: 'Favorite meat?', options: ['Chicken', 'Beef', 'Pork', 'Lamb', 'Fish', 'Vegetarian'] },
  { text: 'Best egg style?', options: ['Scrambled', 'Fried', 'Boiled', 'Omelette', 'Poached', 'Sunny Side Up'] },
  { text: 'Pick a candy!', options: ['Gummy Bears', 'Chocolate Bar', 'Lollipop', 'Sour Candy', 'Hard Candy', 'Marshmallow'] },
  { text: 'Best salad ingredient?', options: ['Chicken', 'Avocado', 'Eggs', 'Croutons', 'Cheese', 'Salmon'] },
  { text: 'Favorite chip flavor?', options: ['Original', 'BBQ', 'Sour Cream', 'Salt & Vinegar', 'Cheese', 'Spicy'] },
  { text: 'Pick a dim sum!', options: ['Har Gow', 'Siu Mai', 'Char Siu Bao', 'Egg Tart', 'Cheung Fun', 'Turnip Cake'] },
  { text: 'Best comfort food?', options: ['Mac & Cheese', 'Fried Chicken', 'Noodle Soup', 'Pizza', 'Rice & Curry', 'Grilled Cheese'] },
  { text: 'Favorite smoothie?', options: ['Banana', 'Mango', 'Berry', 'Green Smoothie', 'Tropical', 'Peanut Butter'] },
  { text: 'Best dumpling type?', options: ['Gyoza', 'Xiao Long Bao', 'Mandu', 'Pierogi', 'Wonton', 'Momo'] },
  { text: 'Pick a topping for toast!', options: ['Butter', 'Jam', 'Avocado', 'Nutella', 'Peanut Butter', 'Cheese'] },
  { text: 'Best fried food?', options: ['French Fries', 'Fried Chicken', 'Tempura', 'Onion Rings', 'Spring Rolls', 'Churros'] },
  { text: 'Favorite juice?', options: ['Orange', 'Apple', 'Watermelon', 'Mango', 'Grape', 'Pineapple'] },
  { text: 'Best date night food?', options: ['Sushi', 'Steak', 'Pasta', 'Korean BBQ', 'Pizza', 'Thai Food'] },
  { text: 'Pick a tea!', options: ['Green Tea', 'Black Tea', 'Oolong', 'Chamomile', 'Earl Grey', 'Jasmine'] },
  { text: 'Best way to eat potato?', options: ['Fries', 'Mashed', 'Baked', 'Chips', 'Hash Browns', 'Wedges'] },
];

const MOVIES = [
  { text: 'Pick a movie genre!', options: ['Romance', 'Action', 'Comedy', 'Horror', 'Sci-Fi', 'Animation'] },
  { text: 'Best Disney movie?', options: ['The Lion King', 'Frozen', 'Tangled', 'Aladdin', 'Moana', 'Up'] },
  { text: 'Favorite superhero?', options: ['Spider-Man', 'Batman', 'Iron Man', 'Thor', 'Wonder Woman', 'Captain America'] },
  { text: 'Pick a Studio Ghibli film!', options: ['Spirited Away', 'Howl\'s Moving Castle', 'My Neighbor Totoro', 'Princess Mononoke', 'Kiki\'s Delivery', 'Ponyo'] },
  { text: 'Best movie snack?', options: ['Popcorn', 'Nachos', 'Candy', 'Ice Cream', 'Hot Dog', 'Nothing'] },
  { text: 'Netflix or cinema?', options: ['Netflix at Home', 'Cinema Date', 'Both Equally', 'Depends on the Movie'] },
  { text: 'Pick an anime!', options: ['One Piece', 'Naruto', 'Attack on Titan', 'Demon Slayer', 'Jujutsu Kaisen', 'My Hero Academia'] },
  { text: 'Best romcom?', options: ['The Notebook', '10 Things I Hate', 'Crazy Rich Asians', 'Love Actually', 'When Harry Met Sally', 'To All the Boys'] },
  { text: 'Favorite TV show type?', options: ['K-Drama', 'Anime', 'Sitcom', 'Reality TV', 'Thriller', 'Documentary'] },
  { text: 'Pick a Harry Potter house!', options: ['Gryffindor', 'Slytherin', 'Ravenclaw', 'Hufflepuff'] },
  { text: 'Best music genre?', options: ['Pop', 'R&B', 'K-Pop', 'Hip Hop', 'Rock', 'Jazz'] },
  { text: 'Favorite K-drama?', options: ['Crash Landing', 'Goblin', 'Squid Game', 'Reply 1988', 'Vincenzo', 'Start-Up'] },
  { text: 'Pick a Pixar movie!', options: ['Finding Nemo', 'Coco', 'Inside Out', 'Ratatouille', 'WALL-E', 'Toy Story'] },
  { text: 'Best video game genre?', options: ['RPG', 'Puzzle', 'Shooter', 'Racing', 'Simulation', 'Fighting'] },
  { text: 'Favorite social media?', options: ['Instagram', 'TikTok', 'YouTube', 'Twitter/X', 'Reddit', 'None'] },
  { text: 'Pick a book genre!', options: ['Romance', 'Fantasy', 'Mystery', 'Self-Help', 'Sci-Fi', 'Biography'] },
  { text: 'Best party song?', options: ['Something Fun', 'Something Chill', 'K-Pop Banger', 'Classic Hit', 'EDM Drop', 'Slow Dance'] },
  { text: 'Movie marathon pick?', options: ['Marvel', 'Harry Potter', 'Lord of the Rings', 'Star Wars', 'Studio Ghibli', 'Disney Classics'] },
  { text: 'Favorite YouTuber type?', options: ['Gaming', 'Cooking', 'Vlog', 'Comedy', 'Education', 'ASMR'] },
  { text: 'Pick a music decade!', options: ['80s', '90s', '2000s', '2010s', '2020s', 'All of Them'] },
  { text: 'Best game console?', options: ['PlayStation', 'Nintendo Switch', 'Xbox', 'PC', 'Mobile', 'Retro Console'] },
  { text: 'Favorite concert type?', options: ['Stadium Show', 'Small Venue', 'Festival', 'Online Stream', 'Acoustic Set', 'Never Been'] },
  { text: 'Pick a cartoon!', options: ['SpongeBob', 'Adventure Time', 'Avatar TLA', 'Tom & Jerry', 'Pokémon', 'Doraemon'] },
  { text: 'Best podcast topic?', options: ['True Crime', 'Comedy', 'Business', 'Relationships', 'Science', 'Don\'t Listen'] },
  { text: 'Favorite board game?', options: ['Monopoly', 'Scrabble', 'Chess', 'UNO', 'Catan', 'Card Games'] },
  { text: 'Pick a karaoke song type!', options: ['Ballad', 'Pop Hit', 'Duet', 'Rock Anthem', 'Disney Song', 'K-Pop'] },
  { text: 'Best streaming service?', options: ['Netflix', 'Disney+', 'YouTube', 'HBO Max', 'Spotify', 'Apple TV+'] },
  { text: 'Favorite emoji?', options: ['😂', '❤️', '🥺', '😭', '🔥', '💀'] },
  { text: 'Pick a phone game!', options: ['Candy Crush', 'Among Us', 'Wordle', 'Subway Surfers', 'Chess', 'Don\'t Play Games'] },
  { text: 'Best way to relax?', options: ['Watch a Movie', 'Listen to Music', 'Play Games', 'Scroll Social Media', 'Read', 'Sleep'] },
  { text: 'Favorite movie era?', options: ['Classic (B&W)', '80s/90s', '2000s', 'Modern', 'No Preference'] },
  { text: 'Pick a dance style!', options: ['K-Pop', 'Hip Hop', 'Salsa', 'Ballet', 'TikTok Dances', 'Can\'t Dance'] },
  { text: 'Best binge show format?', options: ['8 Episodes', '12 Episodes', '20+ Episodes', 'Movie Series', 'Mini-Series', 'Ongoing'] },
  { text: 'Favorite comedy show?', options: ['Friends', 'The Office', 'Brooklyn 99', 'How I Met Your Mother', 'Modern Family', 'Other'] },
  { text: 'Pick a Hogwarts subject!', options: ['Defense Against Dark Arts', 'Potions', 'Charms', 'Care of Magical Creatures', 'Quidditch', 'Herbology'] },
  { text: 'Best movie villain?', options: ['Thanos', 'Joker', 'Voldemort', 'Loki', 'Darth Vader', 'Maleficent'] },
  { text: 'Pick a game to play together!', options: ['Mario Kart', 'Minecraft', 'Overcooked', 'It Takes Two', 'Stardew Valley', 'Just Dance'] },
  { text: 'Favorite app category?', options: ['Social Media', 'Games', 'Productivity', 'Entertainment', 'Shopping', 'Food Delivery'] },
  { text: 'Best movie soundtrack?', options: ['Disney Songs', 'Hans Zimmer', 'John Williams', 'K-Drama OST', 'Anime OST', 'Pop Songs'] },
];

const PLACES = [
  { text: 'Dream vacation spot?', options: ['Japan', 'Paris', 'Bali', 'New York', 'Maldives', 'Switzerland'] },
  { text: 'Beach or mountains?', options: ['Beach', 'Mountains', 'Both', 'Neither — City'] },
  { text: 'Pick a season!', options: ['Spring', 'Summer', 'Autumn', 'Winter'] },
  { text: 'Best date location?', options: ['Cafe', 'Restaurant', 'Park', 'Movie Theater', 'Beach', 'Home'] },
  { text: 'Favorite weather?', options: ['Sunny', 'Rainy', 'Cloudy', 'Snowy', 'Breezy', 'Stormy'] },
  { text: 'Pick a city to live in!', options: ['Tokyo', 'London', 'Sydney', 'Seoul', 'New York', 'Singapore'] },
  { text: 'Best weekend activity?', options: ['Cafe Hopping', 'Hiking', 'Shopping', 'Stay Home', 'Beach Day', 'Food Trip'] },
  { text: 'Favorite room in the house?', options: ['Bedroom', 'Kitchen', 'Living Room', 'Bathroom', 'Balcony', 'Gaming Room'] },
  { text: 'Dream home style?', options: ['Modern', 'Cozy Cottage', 'Minimalist', 'Traditional', 'Loft/Industrial', 'Beach House'] },
  { text: 'Pick a transport!', options: ['Car', 'Train', 'Bicycle', 'Walking', 'Plane', 'Motorcycle'] },
  { text: 'Best honeymoon spot?', options: ['Bali', 'Maldives', 'Paris', 'Santorini', 'Japan', 'Iceland'] },
  { text: 'Favorite park activity?', options: ['Picnic', 'Walk', 'Read a Book', 'Play Sports', 'People Watch', 'Lay on Grass'] },
  { text: 'Pick a country in Asia!', options: ['Japan', 'South Korea', 'Thailand', 'Indonesia', 'Singapore', 'Vietnam'] },
  { text: 'Best place to study/work?', options: ['Cafe', 'Library', 'Home Desk', 'Coworking Space', 'Park', 'Bed'] },
  { text: 'Favorite time of day?', options: ['Morning', 'Afternoon', 'Evening', 'Night', 'Midnight', 'Sunrise'] },
  { text: 'Pick a European city!', options: ['Paris', 'London', 'Barcelona', 'Rome', 'Amsterdam', 'Prague'] },
  { text: 'Beach activity?', options: ['Swimming', 'Sunbathing', 'Surfing', 'Beach Volleyball', 'Build Sandcastle', 'Collect Shells'] },
  { text: 'Favorite store type?', options: ['Bookstore', 'Clothing', 'Tech Store', 'Food Market', 'Thrift Shop', 'Home Decor'] },
  { text: 'Best road trip snack?', options: ['Chips', 'Sandwiches', 'Fruit', 'Candy', 'Fast Food Stops', 'Boba Stops'] },
  { text: 'Pick a nature spot!', options: ['Forest', 'Lake', 'Ocean', 'Mountain Peak', 'Waterfall', 'Garden'] },
  { text: 'Favorite hotel type?', options: ['Luxury Resort', 'Boutique Hotel', 'Airbnb', 'Hostel', 'Camping', 'Ryokan'] },
  { text: 'City or countryside?', options: ['City Life', 'Countryside', 'Suburbs', 'Small Town', 'Depends on Mood'] },
  { text: 'Best festival type?', options: ['Music Festival', 'Food Festival', 'Cultural Festival', 'Art Fair', 'Night Market', 'Cherry Blossom'] },
  { text: 'Pick a theme park!', options: ['Disneyland', 'Universal Studios', 'Legoland', 'Water Park', 'Local Carnival', 'None'] },
  { text: 'Dream island?', options: ['Bali', 'Hawaii', 'Maldives', 'Fiji', 'Jeju Island', 'Phuket'] },
  { text: 'Favorite cafe vibe?', options: ['Cozy & Warm', 'Modern & Clean', 'Garden/Outdoor', 'Book Cafe', 'Cat Cafe', 'Industrial'] },
  { text: 'Best travel companion?', options: ['Just Us Two', 'Small Group', 'Family', 'Solo + Meet Up', 'Big Friend Group', 'Pet'] },
  { text: 'Pick a continent to explore!', options: ['Asia', 'Europe', 'Americas', 'Africa', 'Oceania', 'Antarctica'] },
  { text: 'Favorite market type?', options: ['Night Market', 'Farmers Market', 'Flea Market', 'Fish Market', 'Street Market', 'Online Shopping'] },
  { text: 'Best place to watch sunset?', options: ['Beach', 'Rooftop', 'Mountain', 'Lake', 'Ferris Wheel', 'From Home'] },
  { text: 'Pick a neighborhood vibe!', options: ['Trendy & Hip', 'Quiet & Peaceful', 'Busy & Lively', 'Cultural & Artsy', 'Family-Friendly', 'Near Nature'] },
  { text: 'Favorite museum type?', options: ['Art', 'Science', 'History', 'Interactive/Fun', 'Aquarium', 'Don\'t Like Museums'] },
  { text: 'Dream garden feature?', options: ['Flower Beds', 'Vegetable Patch', 'Hammock', 'Water Feature', 'Fairy Lights', 'Fire Pit'] },
  { text: 'Best winter activity?', options: ['Hot Chocolate Inside', 'Skiing', 'Ice Skating', 'Snow Fight', 'Movie Marathon', 'Travel Somewhere Warm'] },
  { text: 'Pick an adventure!', options: ['Scuba Diving', 'Bungee Jumping', 'Hot Air Balloon', 'Zip Line', 'Paragliding', 'None — Stay Safe'] },
  { text: 'Favorite airport activity?', options: ['Duty Free Shopping', 'Eat Everything', 'Sleep', 'Watch Movies', 'People Watch', 'Explore Lounges'] },
  { text: 'Best staycation idea?', options: ['Cook Together', 'Movie Marathon', 'Spa Day', 'Gaming Session', 'Build a Fort', 'Baking'] },
  { text: 'Rainy day plan?', options: ['Watch Movies', 'Sleep In', 'Cook/Bake', 'Read', 'Play Games', 'Go Out Anyway'] },
  { text: 'Pick a workout spot!', options: ['Gym', 'Home', 'Park', 'Pool', 'Yoga Studio', 'Don\'t Work Out'] },
];

const HABITS = [
  { text: 'Morning person or night owl?', options: ['Morning Person', 'Night Owl', 'Neither', 'Depends on Day'] },
  { text: 'Pick a color!', options: ['Pink', 'Blue', 'Green', 'Purple', 'Black', 'White'] },
  { text: 'Dogs or cats?', options: ['Dogs', 'Cats', 'Both', 'Neither', 'Other Pet', 'All Animals'] },
  { text: 'Texting style?', options: ['Short & Fast', 'Long Messages', 'Voice Notes', 'Memes & Stickers', 'Emojis Everywhere', 'Calls Instead'] },
  { text: 'How do you show love?', options: ['Words', 'Gifts', 'Quality Time', 'Physical Touch', 'Acts of Service', 'All of Them'] },
  { text: 'Favorite love language?', options: ['Words of Affirmation', 'Quality Time', 'Physical Touch', 'Acts of Service', 'Receiving Gifts'] },
  { text: 'Pick a superpower!', options: ['Flying', 'Teleportation', 'Invisibility', 'Time Travel', 'Mind Reading', 'Super Strength'] },
  { text: 'Introvert or extrovert?', options: ['Introvert', 'Extrovert', 'Ambivert', 'Depends on Mood'] },
  { text: 'First thing in the morning?', options: ['Check Phone', 'Brush Teeth', 'Stretch', 'Coffee/Tea', 'Snooze Alarm', 'Shower'] },
  { text: 'Sleeping position?', options: ['Side', 'Back', 'Stomach', 'Fetal Position', 'Changes Every Night', 'Starfish'] },
  { text: 'Pick an animal to be!', options: ['Cat', 'Dog', 'Eagle', 'Dolphin', 'Panda', 'Penguin'] },
  { text: 'How many pillows?', options: ['One', 'Two', 'Three', 'Four+', 'Zero', 'Body Pillow'] },
  { text: 'Favorite way to spend $100?', options: ['Food', 'Clothes', 'Tech/Games', 'Travel Fund', 'Gift for Partner', 'Save It'] },
  { text: 'Best quality in a partner?', options: ['Humor', 'Kindness', 'Intelligence', 'Loyalty', 'Ambition', 'Looks'] },
  { text: 'Pick a zodiac element!', options: ['Fire', 'Water', 'Earth', 'Air', 'Don\'t Believe'] },
  { text: 'Shower: morning or night?', options: ['Morning', 'Night', 'Both', 'Whenever'] },
  { text: 'Favorite clothing style?', options: ['Casual', 'Streetwear', 'Formal', 'Sporty', 'Cozy/Pajamas', 'Minimalist'] },
  { text: 'Pick a hobby!', options: ['Cooking', 'Gaming', 'Reading', 'Sports', 'Art/Crafting', 'Music'] },
  { text: 'Biggest fear?', options: ['Heights', 'Spiders', 'Dark', 'Public Speaking', 'Being Alone', 'Nothing'] },
  { text: 'Phone battery anxiety at?', options: ['50%', '30%', '20%', '10%', '5%', 'Never Worried'] },
  { text: 'Favorite number?', options: ['1', '3', '7', '8', '13', '69'] },
  { text: 'AC temperature setting?', options: ['16°C (Cold!)', '18°C', '20°C', '22°C', '24°C', '26°C+ (Warm)'] },
  { text: 'Left or right side of bed?', options: ['Left', 'Right', 'Middle', 'Doesn\'t Matter', 'Whole Bed'] },
  { text: 'Pick a month!', options: ['January', 'April', 'June', 'August', 'October', 'December'] },
  { text: 'Best life advice?', options: ['Be Kind', 'Work Hard', 'Follow Your Heart', 'Stay Positive', 'Take Risks', 'Love More'] },
  { text: 'Nail biter?', options: ['Yes Always', 'Sometimes', 'Used To', 'Never', 'Didn\'t Know I Do'] },
  { text: 'Pick a scent!', options: ['Vanilla', 'Lavender', 'Fresh Linen', 'Ocean Breeze', 'Coffee', 'Rain'] },
  { text: 'How do you argue?', options: ['Talk It Out', 'Need Space First', 'Write It Down', 'Get Emotional', 'Avoid It', 'Apologize Fast'] },
  { text: 'Favorite day of the week?', options: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday', 'Every Day Same'] },
  { text: 'Best emoji to describe you?', options: ['😊', '🤪', '😎', '🥰', '😴', '🤔'] },
  { text: 'Pick a random skill!', options: ['Cooking', 'Dancing', 'Singing', 'Drawing', 'Photography', 'Coding'] },
  { text: 'Night routine?', options: ['Skincare', 'Scroll Phone', 'Read', 'Watch TV', 'Talk to Partner', 'Straight to Sleep'] },
  { text: 'How do you de-stress?', options: ['Exercise', 'Eat Good Food', 'Talk to Someone', 'Be Alone', 'Sleep', 'Watch Something'] },
  { text: 'Alarm style?', options: ['One Alarm', 'Many Alarms', 'Natural Wake Up', 'Partner Wakes Me', 'Vibration Only', 'No Alarm Needed'] },
  { text: 'Pick a weather mood!', options: ['Sunshine = Happy', 'Rain = Cozy', 'Snow = Magical', 'Wind = Free', 'Cloudy = Calm', 'Any Weather'] },
  { text: 'Ideal dinner time?', options: ['5-6 PM', '6-7 PM', '7-8 PM', '8-9 PM', '9-10 PM', 'After 10 PM'] },
  { text: 'Best way to say sorry?', options: ['In Person', 'Long Text', 'With Food', 'With a Hug', 'Give Space Then Talk', 'Write a Letter'] },
  { text: 'Shoes off at home?', options: ['Always Off', 'Slippers', 'Keep Shoes On', 'Socks Only', 'Barefoot'] },
  { text: 'How many tabs open?', options: ['1-3', '4-10', '11-20', '21-50', '50+', 'Too Many to Count'] },
  { text: 'Toilet paper: over or under?', options: ['Over', 'Under', 'Don\'t Care', 'Bidet Gang'] },
  { text: 'Pick an era to visit!', options: ['Dinosaurs', 'Ancient Egypt', 'Medieval', '1920s', 'Future (2100)', 'Stay in Present'] },
  { text: 'Favorite time to nap?', options: ['After Lunch', 'Afternoon', 'Evening', 'Don\'t Nap', 'Anytime', 'Always Napping'] },
];

const PARTNER = [
  { text: 'What color would sayang pick?', options: ['Pink', 'Blue', 'Green', 'Purple', 'Black', 'White'] },
  { text: 'What\'s sayang\'s go-to snack?', options: ['Chips', 'Chocolate', 'Fruit', 'Ice Cream', 'Cookies', 'Instant Noodles'] },
  { text: 'How would sayang spend a free day?', options: ['Sleep In', 'Go Out & Explore', 'Play Games', 'Watch Movies', 'Eat Good Food', 'Be With You'] },
  { text: 'What makes sayang happiest?', options: ['Good Food', 'Quality Time', 'Compliments', 'Surprises', 'Physical Touch', 'Achievements'] },
  { text: 'What would sayang order at a cafe?', options: ['Coffee', 'Boba Tea', 'Cake', 'Matcha', 'Smoothie', 'Hot Chocolate'] },
  { text: 'Sayang\'s biggest pet peeve?', options: ['Late Replies', 'Being Late', 'Loud Chewing', 'Messy Room', 'Dishonesty', 'Being Ignored'] },
  { text: 'What would sayang binge watch?', options: ['K-Drama', 'Anime', 'Comedy', 'True Crime', 'Reality TV', 'YouTube'] },
  { text: 'Sayang\'s dream job?', options: ['CEO', 'Chef', 'Artist', 'Traveler', 'Gamer', 'Stay at Home'] },
  { text: 'What scares sayang most?', options: ['Spiders', 'Heights', 'The Dark', 'Horror Movies', 'Being Alone', 'Nothing'] },
  { text: 'Sayang\'s comfort food?', options: ['Fried Chicken', 'Noodle Soup', 'Pizza', 'Rice & Curry', 'Ice Cream', 'Instant Noodles'] },
  { text: 'If sayang won the lottery?', options: ['Travel the World', 'Buy a House', 'Invest', 'Shopping Spree', 'Treat Family', 'Quit Everything'] },
  { text: 'Sayang\'s texting speed?', options: ['Lightning Fast', 'Pretty Quick', 'Normal', 'Slow Reader', 'Replies Hours Later', 'Left on Read Expert'] },
  { text: 'What would sayang cook?', options: ['Fried Rice', 'Pasta', 'Instant Noodles', 'Nothing — Order In', 'Something Fancy', 'Scrambled Eggs'] },
  { text: 'Sayang\'s energy level?', options: ['Always Hyper', 'Morning Only', 'Night Owl Energy', 'Chill Vibes', 'Sleepy Always', 'Depends on Food'] },
  { text: 'What gift would sayang love?', options: ['Tech Gadget', 'Fashion Item', 'Food/Snacks', 'Handwritten Letter', 'Experience/Trip', 'Flowers'] },
  { text: 'Sayang at a party?', options: ['Life of the Party', 'In the Corner', 'With Close Friends', 'Near the Food', 'On the Phone', 'Left Already'] },
  { text: 'What would sayang major in?', options: ['Business', 'Art/Design', 'Computer Science', 'Psychology', 'Culinary', 'Music'] },
  { text: 'Sayang\'s phone screen time?', options: ['1-2 Hours', '3-4 Hours', '5-6 Hours', '7-8 Hours', '9+ Hours', 'Don\'t Ask'] },
  { text: 'Sayang\'s sleep schedule?', options: ['Before 10 PM', '10 PM-12 AM', '12-2 AM', 'After 2 AM', 'No Schedule', 'Whenever They Drop'] },
  { text: 'What would sayang rescue first in a fire?', options: ['Phone', 'Pet', 'Photo Album', 'Laptop', 'Snacks', 'You'] },
  { text: 'Sayang\'s hidden talent?', options: ['Singing', 'Cooking', 'Dancing', 'Drawing', 'Making People Laugh', 'Sleeping Anywhere'] },
  { text: 'Sayang\'s catchphrase?', options: ['LOL', 'Hahaha', 'Bruh', 'OMG', 'Sayang~', 'Hmm'] },
  { text: 'What would sayang name a pet?', options: ['Food Name', 'Human Name', 'Cute Name', 'Funny Name', 'Character Name', 'Their Own Name'] },
  { text: 'Sayang\'s reaction to a spider?', options: ['Scream & Run', 'Kill It', 'Catch & Release', 'Call for Help', 'Ignore It', 'Take a Photo'] },
  { text: 'What does sayang do when bored?', options: ['Scroll Phone', 'Eat', 'Sleep', 'Text You', 'Clean', 'Start a Project'] },
  { text: 'Sayang\'s ideal weekend?', options: ['Stay Home', 'Go Shopping', 'Nature Trip', 'Food Tour', 'Gaming All Day', 'Date Night'] },
  { text: 'What would sayang wear to a costume party?', options: ['Funny Costume', 'Cute/Couple Costume', 'Low Effort', 'All Out Dramatic', 'Last Minute DIY', 'Skip the Party'] },
  { text: 'Sayang when they\'re hangry?', options: ['Silent & Moody', 'Snappy', 'Dramatic', 'Just Eats Anything', 'Denies Being Hungry', 'Becomes a Monster'] },
  { text: 'Sayang\'s karaoke style?', options: ['Power Ballad', 'Rap God', 'Off-Key But Passionate', 'Shy Whisperer', 'Crowd Hype', 'Refuses to Sing'] },
  { text: 'What would sayang google at 3 AM?', options: ['Food Near Me', 'Random Facts', 'Conspiracy Theories', 'Shopping', 'Am I Sick?', 'Cute Animals'] },
  { text: 'Sayang\'s Disney character?', options: ['Rapunzel', 'Simba', 'Stitch', 'Elsa', 'Baymax', 'Olaf'] },
  { text: 'What would sayang forget?', options: ['Keys', 'Wallet', 'Phone', 'Anniversary', 'To Eat', 'Names'] },
  { text: 'Sayang\'s emoji usage?', options: ['Every Message', 'Sometimes', 'Rarely', 'Only ❤️', 'Only 😂', 'Zero Emojis'] },
  { text: 'If sayang could time travel?', options: ['Fix a Mistake', 'See the Future', 'Meet Historical Figure', 'Relive Best Memory', 'Invest Early', 'Stay Present'] },
  { text: 'Sayang as an ice cream flavor?', options: ['Vanilla (Classic)', 'Chocolate (Rich)', 'Strawberry (Sweet)', 'Mint (Refreshing)', 'Cookie Dough (Fun)', 'Spicy Mango (Unique)'] },
  { text: 'What does sayang do on long flights?', options: ['Sleep', 'Watch Movies', 'Read', 'Eat All Snacks', 'Talk to Neighbors', 'Stress About Landing'] },
  { text: 'Sayang\'s spirit animal?', options: ['Cat (Independent)', 'Dog (Loyal)', 'Panda (Chill)', 'Eagle (Free)', 'Otter (Playful)', 'Sloth (Relaxed)'] },
  { text: 'What would sayang put on a dating profile?', options: ['Funny Bio', 'Food Pics', 'Travel Photos', 'Dog/Cat Pics', 'Gym Selfie', 'Wouldn\'t Have One'] },
  { text: 'Sayang\'s most used app?', options: ['Instagram', 'TikTok', 'YouTube', 'WhatsApp', 'Games', 'Food Delivery'] },
  { text: 'Sayang on a roller coaster?', options: ['Screaming', 'Laughing', 'Eyes Closed', 'Hands Up', 'Regretting Everything', 'Refusing to Go On'] },
];

function tagged(category, questions) {
  return questions.map((q) => ({ ...q, category }));
}

export const ALL_QUESTIONS = [
  ...tagged('food', FOOD),
  ...tagged('movies', MOVIES),
  ...tagged('places', PLACES),
  ...tagged('habits', HABITS),
  ...tagged('partner', PARTNER),
];

export function pickQuestions(count = 10, bonusCount = 2) {
  const regular = ALL_QUESTIONS.filter((q) => q.category !== 'partner');
  const bonus = ALL_QUESTIONS.filter((q) => q.category === 'partner');

  shuffle(regular);
  shuffle(bonus);

  const picked = [
    ...regular.slice(0, count).map((q) => ({ ...q, isBonus: false })),
    ...bonus.slice(0, bonusCount).map((q) => ({ ...q, isBonus: true })),
  ];

  return picked;
}

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}
